### ISSUE TITLE
Error!!!

### ISSUE THREAD

**Issue by gizmo4546** [adeept/Adeept_RFID_Learning_Kit_C_Code_for_RPi#2]
When I go to compile I get
buzzer.c: in function ‘main’:
buzzer.c:13:25: error: expected ‘)’ before ‘;’ token 
pinMode(Beeppin, OUTPUT; //set GPIO0
                                               ^
buzzer.c:23:1: error: expected ‘;’ before ‘}’ token
}
^

**Comment by Zodark** [comment]
You missed the closing parentheses. 
Change that line to:
pinMode(Beeppin, OUTPUT);

**Comment by gizmo4546** [comment]
Thank you ✌🏻
